import { readFile, stat, writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import { NodeIO } from "@gltf-transform/core";
import { ALL_EXTENSIONS } from "@gltf-transform/extensions";
import { dedup, weld, meshopt } from "@gltf-transform/functions";
import { MeshoptEncoder } from "meshoptimizer";
import sharp from "sharp";

const source = "design/audi-s4/ali-s4-source.glb";
const output = "public/models/ali-s4.glb";
const poster = "public/models/ali-s4-poster.webp";
await MeshoptEncoder.ready;
const io = new NodeIO().registerExtensions(ALL_EXTENSIONS).registerDependencies({ "meshopt.encoder": MeshoptEncoder });
const document = await io.read(source);
await document.transform(dedup(), weld(), meshopt({ encoder: MeshoptEncoder, level: "high", quantizePosition: 16, quantizeNormal: 12, quantizeTexcoord: 14 }));
await io.write(output, document);
await sharp("design/audi-s4/front-review.png")
  .trim()
  .resize(1440, 900, { fit: "contain", background: { r: 0, g: 0, b: 0, alpha: 0 } })
  .webp({ quality: 88, alphaQuality: 100 })
  .toFile(poster);
const revision = async (path) => createHash("sha256").update(await readFile(path)).digest("hex").slice(0, 12);
const metadata = `// Generated by npm run car:assets. Both scenes use this revision.\nexport const s4ModelUrl = "/models/ali-s4.glb?v=${await revision(output)}";\nexport const s4Poster = {\n  src: "/models/ali-s4-poster.webp?v=${await revision(poster)}",\n  width: 1440,\n  height: 900,\n};\n`;
const metadataPath = "src/data/s4.js";
if (await readFile(metadataPath, "utf8").catch(() => "") !== metadata) await writeFile(metadataPath, metadata);
const before = (await stat(source)).size;
const after = (await stat(output)).size;
console.log(`S4: ${(before / 1e6).toFixed(2)} MB → ${(after / 1e6).toFixed(2)} MB. Saved ${Math.round((1 - after / before) * 100)}%.`);
