// scripts/optimize-world.mjs: the city's two GLBs, from one Blender export.
//
// `npm run world:assets`, after scripts/blender/build_night_city_world.py has
// written design/night-city-world/world-source.glb. Produces:
//
//   public/scenes/world/world-high.glb   desktop: everything, 1K WebP maps
//   public/scenes/world/world-phone.glb  phone: no `detail` meshes (the rails,
//                                        units, lanterns and clutter tagged in
//                                        Blender), 512 px maps
//   public/scenes/world/moon.webp        the intro's moon still, for the
//                                        Contact shot's moon
//   public/scenes/world/holo.webp        the avenue's holographic figure
//   src/data/world-assets.js             their URLs, with a content hash so
//                                        a rebuilt city replaces a cached one
//
// Only the road keeps a roughness map: the site's wet-road shader reads it
// for the puddles. Every other surface is flat paint or the facade shader,
// so their roughness maps would be bytes nobody draws. Budgets from the
// brief are asserted here, so a build that outgrows them fails loudly.
import { mkdir, readFile, stat, writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import { NodeIO } from "@gltf-transform/core";
import { ALL_EXTENSIONS } from "@gltf-transform/extensions";
import { dedup, weld, meshopt, prune, textureCompress } from "@gltf-transform/functions";
import { MeshoptEncoder } from "meshoptimizer";
import sharp from "sharp";

const SOURCE = "design/night-city-world/world-source.glb";
const OUT = "public/scenes/world";
const BUDGET = { high: 3.5e6, phone: 1.5e6 };
const TIERS = {
  high: { size: 1024, quality: 82, dropDetail: false },
  phone: { size: 512, quality: 76, dropDetail: true },
};

await MeshoptEncoder.ready;
const io = new NodeIO()
  .registerExtensions(ALL_EXTENSIONS)
  .registerDependencies({ "meshopt.encoder": MeshoptEncoder });

await mkdir(OUT, { recursive: true });
const sizes = {};

for (const [tier, opts] of Object.entries(TIERS)) {
  const document = await io.read(SOURCE);
  const root = document.getRoot();

  // Roughness maps: the road's only.
  for (const material of root.listMaterials()) {
    if (material.getName() !== "NCW_asphalt") material.setMetallicRoughnessTexture(null);
  }

  // The phone drops everything Blender tagged as detail.
  if (opts.dropDetail) {
    for (const node of root.listNodes()) {
      if (node.getExtras()?.detail === 1) node.dispose();
    }
  }

  await document.transform(
    // keepLeaves: the anchors and cameras are empty nodes, and they are the
    // whole point of reading this file by name. keepAttributes: the facades'
    // UVs are window cells and their colours are per-building parameters for
    // the site's shaders, which no glTF texture references.
    prune({ keepLeaves: true, keepExtras: true, keepAttributes: true }),
    dedup(),
    weld(),
    textureCompress({ encoder: sharp, targetFormat: "webp", resize: [opts.size, opts.size], quality: opts.quality }),
    meshopt({ encoder: MeshoptEncoder, level: "high", quantizePosition: 16, quantizeNormal: 10, quantizeTexcoord: 14 }),
  );
  const path = `${OUT}/world-${tier}.glb`;
  await io.write(path, document);
  sizes[tier] = (await stat(path)).size;
  let triangles = 0;
  for (const mesh of root.listMeshes()) {
    for (const prim of mesh.listPrimitives()) triangles += (prim.getIndices()?.getCount() ?? 0) / 3;
  }
  console.log(`world-${tier}.glb: ${(sizes[tier] / 1e6).toFixed(2)} MB, ${root.listMeshes().length} meshes, ` +
    `${triangles.toLocaleString()} triangles, ${root.listTextures().length} textures`);
  if (sizes[tier] > BUDGET[tier]) {
    throw new Error(`world-${tier}.glb is ${(sizes[tier] / 1e6).toFixed(2)} MB, over its ${BUDGET[tier] / 1e6} MB budget`);
  }
}

// The moon: the intro's own still, for the disc over the Contact shot.
const moonPath = `${OUT}/moon.webp`;
await sharp("design/night-city-garage/textures/moon.jpg").webp({ quality: 86 }).toFile(moonPath);
console.log(`moon.webp: ${Math.round((await stat(moonPath)).size / 1024)} KB`);

// The holographic figure at the end of the avenue: an original generated
// image (design/night-city-world/README.md records how), additive on black.
const holoPath = `${OUT}/holo.webp`;
await sharp("design/night-city-world/textures/holo-figure.jpg").resize(768, 1152).webp({ quality: 82 }).toFile(holoPath);
console.log(`holo.webp: ${Math.round((await stat(holoPath)).size / 1024)} KB`);

const revision = async (path) => createHash("sha256").update(await readFile(path)).digest("hex").slice(0, 12);
const base = "/scenes/world/";
const metadata = `// Generated by npm run world:assets (scripts/optimize-world.mjs). Do not edit.
export const worldModelUrl = {
  high: "${base}world-high.glb?v=${await revision(`${OUT}/world-high.glb`)}",
  phone: "${base}world-phone.glb?v=${await revision(`${OUT}/world-phone.glb`)}",
};
export const worldMoonUrl = "${base}moon.webp?v=${await revision(moonPath)}";
export const worldHoloUrl = "${base}holo.webp?v=${await revision(holoPath)}";
`;
const metadataPath = "src/data/world-assets.js";
if ((await readFile(metadataPath, "utf8").catch(() => "")) !== metadata) await writeFile(metadataPath, metadata);
console.log(`budgets: high ${(sizes.high / 1e6).toFixed(2)} / 3.5 MB, phone ${(sizes.phone / 1e6).toFixed(2)} / 1.5 MB`);
